import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1c1b',
        'on-secondary-container': '#386b69',
        'secondary-container': '#b5eae7',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f1f1ef',
        'primary-fixed': '#cceace',
        'on-primary-fixed-variant': '#334d38',
        'inverse-surface': '#2f3130',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#093e3d',
        'on-primary-container': '#233d29',
        'primary-fixed-dim': '#b0ceb2',
        outline: '#737972',
        'surface-container-high': '#e9e8e6',
        tertiary: '#386664',
        'surface-container-low': '#f4f3f1',
        'surface-bright': '#faf9f7',
        surface: '#faf9f7',
        'secondary-fixed': '#b8ecea',
        'tertiary-fixed': '#bbece9',
        'on-surface-variant': '#424842',
        'on-secondary-fixed': '#00201f',
        'tertiary-fixed-dim': '#a0cfcd',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#1e4e4c',
        'primary-container': '#8ba88e',
        'surface-container': '#efeeec',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#07200f',
        'error-container': '#ffdad6',
        'surface-tint': '#4a654e',
        'outline-variant': '#c2c8c0',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'tertiary-container': '#7ba9a7',
        secondary: '#346665',
        background: '#faf9f7',
        'secondary-fixed-dim': '#9cd0cd',
        'on-background': '#1a1c1b',
        primary: '#4a654e',
        'on-tertiary-fixed': '#00201f',
        'on-error-container': '#93000a',
        'inverse-primary': '#b0ceb2',
        'surface-dim': '#dadad8',
        'surface-variant': '#e3e2e0',
        'on-secondary-fixed-variant': '#194e4d',
        'surface-container-highest': '#e3e2e0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        gutter: '24px',
        'stack-md': '24px',
        'margin-mobile': '16px',
        'stack-lg': '48px',
        'stack-sm': '12px',
        'container-max': '1200px',
        base: '8px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
      },
      boxShadow: {
        ambient: '0 12px 24px -4px rgba(26, 28, 27, 0.05)',
        'soft': '0 12px 24px -10px rgba(26, 28, 27, 0.1)',
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [forms],
}

export default config
