import { SiteHeader, SiteFooter } from '@/components/SiteHeader'

export default function PrivacyPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <SiteHeader showExit={false} />
      <main className="flex-grow max-w-2xl mx-auto px-margin-mobile py-stack-lg">
        <h1 className="font-headline-xl-mobile text-headline-xl-mobile text-on-surface mb-8">Privacy Policy</h1>

        <div className="prose prose-neutral max-w-none space-y-6 font-body-md text-on-surface-variant">
          <section>
            <h2 className="font-headline-md text-on-surface mb-3">What we collect</h2>
            <p>Urushi collects only what is necessary to run the facilitation process: your name, contact information (email or phone), and the private messages you send during the intake process.</p>
          </section>

          <section>
            <h2 className="font-headline-md text-on-surface mb-3">How we protect your data</h2>
            <p>All private intake messages and submission summaries are encrypted at rest using AES-256-GCM encryption. Only the server can decrypt them, and they are never returned to the browser of another participant.</p>
          </section>

          <section>
            <h2 className="font-headline-md text-on-surface mb-3">What the other participant can see</h2>
            <p>The other participant in your conversation <strong>cannot see your raw intake messages or submission</strong>. They can only see the shared report, which is a neutral synthesis generated by the AI. They can see your first name and the discussion topic.</p>
          </section>

          <section>
            <h2 className="font-headline-md text-on-surface mb-3">AI processing</h2>
            <p>Your private submission summary is sent to OpenAI&apos;s API solely for the purpose of generating your shared report. It is not used to train OpenAI models and is subject to OpenAI&apos;s data processing terms.</p>
          </section>

          <section>
            <h2 className="font-headline-md text-on-surface mb-3">Data retention</h2>
            <p>Case data is retained for 90 days after the case is closed. You may request deletion of your submission at any time before analysis begins.</p>
          </section>

          <section>
            <h2 className="font-headline-md text-on-surface mb-3">Third parties</h2>
            <p>We use Supabase for database hosting, OpenAI for AI processing, and optionally Resend for email notifications and WhatsApp Cloud API for WhatsApp notifications. We do not sell your data to third parties.</p>
          </section>

          <section>
            <h2 className="font-headline-md text-on-surface mb-3">Analytics</h2>
            <p>No third-party analytics are used on private intake, waiting, or report pages. This prototype does not use tracking pixels or behavioural analytics.</p>
          </section>
        </div>
      </main>
      <SiteFooter />
    </div>
  )
}
